version: '3.7'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/opt
    ports:
      - "3000:3000"
  fetch:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/opt
    stdin_open: true
    tty: true
